# Generated by Django 5.2.4 on 2025-07-24 07:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tag_locations_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
        migrations.RenameModel(
            old_name='Preferences',
            new_name='Preference',
        ),
        migrations.AlterModelTable(
            name='location',
            table='app_locations',
        ),
    ]
