# Generated by Django 5.2.4 on 2025-07-24 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_locations_location_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table=None,
        ),
    ]
