# Generated by Django 5.2.4 on 2025-08-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_location_address_location_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='address',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='type',
        ),
    ]
